services:
  client:
    image: faizms14/sio-client:latest
    container_name: sio-app-client
    networks:
      - proxy_net
    labels:
      traefik.enable: "true"
      traefik.docker.network: proxy_net
      traefik.http.routers.sio-client.rule: "Host(`sioms.faizms.com`)"
      traefik.http.routers.sio-client.entrypoints: websecure
      traefik.http.routers.sio-client.tls: "true"
      traefik.http.routers.sio-client.tls.certresolver: myresolver
      traefik.http.services.sio-client.loadbalancer.server.port: "80"
    restart: unless-stopped

networks:
  proxy_net:
    external: true